abbr -a -- gco 'git checkout'
abbr -a -- gcb 'git checkout -b'
abbr -a -- gst 'git status'
abbr -a -- g git
abbr -a -- gsta 'git stash'
abbr -a -- gstp 'git stash pop'
abbr -a -- ga 'git add'
abbr -a -- gc 'git commit'
abbr -a -- gba 'git branch --all'
abbr -a -- gbd 'git branch --delete'
abbr -a -- gbD 'git branch --delete --force'
abbr -a -- grba 'git rebase --abort'
abbr -a -- grbc 'git rebase --continue'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gcm 'git checkout main'
abbr -a -- gc! 'git commit --verbose --amend'
abbr -a -- gd 'git diff'
abbr -a -- gdca 'git diff --cached'
abbr -a -- glog 'git log --graph --oneline --decorate'
abbr -a -- gl 'git pull'
abbr -a -- gp 'git push'
abbr -a -- grbi 'git rebase --interactive'
