abbr -a -- k kubectl
abbr -a -- kaf 'kubectl apply -f'
abbr -a -- keti 'kubectl exec -it'
abbr -a -- kcuc 'kubectl config use-context'
abbr -a -- kcgc 'kubectl config get-contexts'
abbr -a -- kdel 'kubectl delete'
abbr -a -- kge 'kubectl get events --sort-by=.lastTimestamp'
abbr -a -- kgp 'kubectl get pods'
abbr -a -- kgpn 'kubectl get pods -n'
abbr -a -- kdelp 'kubectl delete pod'
abbr -a -- kdp 'kubectl describe pods'
abbr -a -- kgs 'kubectl get svc'
abbr -a -- kds 'kubectl describe svc'
abbr -a -- kgcm 'kubectl get configmaps'
abbr -a -- kecm 'kubectl edit configmaps'
abbr -a -- kgsec 'kubectl get secret'
abbr -a -- kdcm 'kubectl describe configmaps'
abbr -a -- kl 'kubectl logs'
